site_name: ObservML
nav :
  - Home : index.md
  
  - "Getting Started": 
    - "Local Development" : localdev.md
    - "Docker Deployment" : serve.md
    - "Client Usage and Testing": client.md
  
  - "Core Components":
    - "API Reference": api.md
    - "Configuration": configuration.md
    - "Plugin System": plugin_system.md
    - "Plugins": plugins.md
  
  - "Framework":
    - "Models": models.md
    - "Experiments": experiments.md
    - "Test Results" : test_results.md
  
  - "Development":
    - "Roadmap": roadmap.md

plugins:
  - print-site # pip install mkdocs-pdf-export-plugin + /print_page/ + print browser
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append('../')
          selection:
            new_path_syntax: true


theme: readthedocs
