load_object :
  module: framework.TimeSeriesAnalysis
  name:  TimeSeriesAnomalyExperiment
setup: 
    datetime_column : "ds"
    datetime_format : "ms" 
    target : "y"

eda:    
create_model :
    model : "arima" # Random Forest
    params:
      start_p : 10
      d : 
      start_q : 10
      max_p : 100
      max_q : 100
      seasonal : False
      threshold_for_anomaly : 3