load_object :
  module: framework.FaultIsolation
  name: FaultIsolationExperiment


setup:
    datetime_column : ds
    datetime_format : "ms" 
    target : "Output (S)"
eda:
create_model :
    model : "mc" # Random Forest
    params: ## No params.